;AUTHOR: PRAVEEN 
;DATE: 09/28/2016
;ESD LAB 2-REQUIRED AND SUPPLEMENTAL ELEMENTS
      ORG 000H				; STARTING ADDRESS AT 0000H
 JMP BEGIN		; jump to the main program
       
      ORG 000BH				; timer 0 interrupt vector
 JMP ISR_Timer0		; jump to timer 0 ISR
       
       
BEGIN: 				;MAIN PROGRAM
MOV TMOD, #1	      ; SET TIMER MODE AS 16 BIT COUNTER
 MOV R7,#0      	;R7 REGISTER IS USED TO KEEP COUNT OF TIMER LOAD VALUE IN THE ISR
 MOV IE,#82H		;ENABLE TIMER 0 INTERRUPT ALON
 MOV TH0, #05CH		; SET TIMER HIGH COUNT VALUE
 MOV TL0, #033H		; SET TIMER LOW COUNT VAL
 SETB TR0			;START TIMER 0
MOV R6,#000H		;R6 IS USED TO INCREMENT VALUES TO BE WRITTEN FROM 00-7FH IN THE 734
MOV R5,#080H		;R5 IS USED TO INCREMENT VALUES TO BE WRITTEN FROM 80-FFH IN THE 734
INF_LOOP:			; INFINITE LOOP THAT EXECUTES BETWEEN ISRS
MOV A,R6			; MOV VALUE OF R6 TO ACC
MOVX @DPTR,A			; WRITE ACC VALUE TO EXTERNAL MEMORY ON P0
INC R6				; INCREMENT R6
CJNE R6,#07FH, CONTINUE; IF R6 IS NOT EQUAL TO 7FH, GOTO CONTINUE LABEL
MOV A,R6			; MOV VALUE OF R6 TO ACC
MOVX @DPTR,A			; WRITE ACC VALUE TO EXTERNAL MEMORY ON P0
MOV R6,#000H		; REINTIALIZE R6 TO 0H
CONTINUE:     
JMP INF_LOOP				;INFINTE LOOP JUMPING TO ITSELF
     	
ISR_Timer0:			; TIMER0 ISR
SETB P1.0			;1C;SET PORT 1 PIN (UNSUSED PIN) AS DESCRIBED IN THE ASSIGNMENT
MOV A,R5			; MOV VALUE OF R5 TO ACC
MOVX @DPTR,A			; WRITE ACC VALUE TO EXTERNAL MEMORY ON P0
INC R5				; INCREMENT R5
CJNE R5,#0FFH,CONTINUE2; IF R5 IS NOT EQUAL TO FFH, GOTO CONTINUE2 LABEL
MOV A,R5			; MOV VALUE OF R5 TO ACC
MOVX @DPTR,A			; WRITE ACC VALUE TO EXTERNAL MEMORY ON P0
MOV R5,#080H		; REINTIALIZE R5 TO 80H
CONTINUE2:
INC R7				 ;1C;INCREMENT R0 VALUE 
CJNE R7,#10,NO_BLINK ;2C;IF R0 IS NOT EQUAL TO 10, JUMP TO NO_BLINK
CPL P1.1			  ;1C; IF R0 IS 10, BLINK LED CONNETED TO P1.1
MOV R7,#0			  ;1C	; SET R0 VALUE TO 0
NO_BLINK: 				; NO_BLINK LABEL
MOV TH0, #05CH	 	;2C	; SET TIMER HIGH COUNT VALUE
MOV TL0, #033H		;2C	; SET TIMER LOW COUNT VALUE
CLR P1.0		;1C; CLEAR PORT 1 PIN(UNUSED PIN) AT END OF ISR, AS DESCRIBED IN ASSIGNMENT
RETI			;2C; return from interrupt BACK TO INFINTE LOOP 
