;AUTHOR: PRAVEEN 
;DATE: 09/23/2016
;ESD LAB 2-REQUIRED ELEMENTS
      ORG 000H				; STARTING ADDRESS AT 0000H
 JMP BEGIN		; jump to the main program
       
      ORG 000BH				; timer 0 interrupt vector
 JMP ISR_Timer0		; jump to timer 0 ISR
       
       
BEGIN: 				;MAIN PROGRAM
MOV TMOD, #1	      ; SET TIMER MODE AS 16 BIT COUNTER
 MOV R0,#0      	;R0 REGISTER IS USED TO KEEP COUNT OF TIMER LOAD VALUE IN THE ISR
 MOV IE,#82H		;ENABLE TIMER 0 INTERRUPT ALON
 MOV TH0, #05CH		; SET TIMER HIGH COUNT VALUE
 MOV TL0, #033H		; SET TIMER LOW COUNT VALUE
 SETB TR0			;START TIMER 0
     
JMP $				;INFINTE LOOP JUMPING TO ITSELF
     	
ISR_Timer0:			; TIMER0 ISR
SETB P1.0			;1C;SET PORT 1 PIN (UNSUSED PIN) AS DESCRIBED IN THE ASSIGNMENT
INC R0				 ;1C;INCREMENT R0 VALUE 
CJNE R0,#10,NO_BLINK ;2C;IF R0 IS NOT EQUAL TO 10, JUMP TO NO_BLINK
CPL P1.1			  ;1C; IF R0 IS 10, BLINK LED CONNETED TO P1.1
MOV R0,#0			  ;1C	; SET R0 VALUE TO 0
NO_BLINK: 				; NO_BLINK LABEL
MOV TH0, #05CH	 	;2C	; SET TIMER HIGH COUNT VALUE
MOV TL0, #033H		;2C	; SET TIMER LOW COUNT VALUE
CLR P1.0		;1C; CLEAR PORT 1 PIN(UNUSED PIN) AT END OF ISR, AS DESCRIBED IN ASSIGNMENT
RETI			;2C; return from interrupt BACK TO INFINTE LOOP 
